### ISSUE TITLE
Failing on Meteor 1.0.4?

### ISSUE THREAD

**Issue by AnthonyAstige** [meteorhacks/meteor-aggregate#12]
Here's the error I'm getting which I think originates from this package

    Exception while invoking method 'usdaLoadFoods' TypeError: Object [object Object] has no method '_getCollection'
    I20150320-19:27:33.437(-5)?     at [object Object].MongoInternals.Connection.aggregate (packages/meteorhacks:aggregate/index.js:2:1)
    I20150320-19:27:33.437(-5)?     at [object Object].Mongo.Collection.aggregate (packages/meteorhacks:aggregate/index.js:21:1)

There were some Mongo updates mentioned in [the Meteor 1.0.4 announcement] (https://www.meteor.com/blog/2015/03/17/meteor-104-mongo-cordova-template-subscriptions) I wonder if are related.

**Comment by AnthonyAstige** [comment]
If there's issues with my pull request let me know; I'm new to them.  It works on my local though I haven't tested it at all extensively.

**Comment by dweldon** [comment]
Is there any reason why I'd be getting:

```
TypeError: Object [object Object] has no method '_getCollection'
```

When using meteor 1.1? I'm trying to use meteor-aggregate from within a package... do I need to `api.use` something other than `meteorhacks:aggregate`?
