### ISSUE TITLE
TypeError: Object [object Object] has no method 'aggregate'

### ISSUE THREAD

**Issue by ericchen0121** [meteorhacks/meteor-aggregate#7]
When I add `meteor-aggregate` to my project, running this code: 

```
var metrics = new Mongo.Collection('metrics');
metrics.insert({ sport: 'NFL', contestName: 'eric', entrySize: 35});
metrics.insert({ sport: 'NFL', contestName: 'bobby', entrySize: 30});

var pipeline = [{ $match : { sport : 'NFL'}}, {$project: {contestName: 1, entrySize: 1}}];
metrics.aggregate(pipeline);
var result = metrics.aggregate(pipeline);
```

I get this error: 
```
W20150111-02:46:41.515(-8)? (STDERR) /Users/SavvyMac/.meteor/packages/meteor-tool/.1.0.38.ydz5xy++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150111-02:46:41.516(-8)? (STDERR) 						throw(ex);
W20150111-02:46:41.516(-8)? (STDERR) 						      ^
W20150111-02:46:41.520(-8)? (STDERR) TypeError: Object [object Object] has no method 'aggregate'
W20150111-02:46:41.522(-8)? (STDERR)     at app/server/lib/test.js:9:22
W20150111-02:46:41.522(-8)? (STDERR)     at app/server/lib/test.js:12:3
W20150111-02:46:41.523(-8)? (STDERR)     at /Users/SavvyMac/code/meteor-learning/people-match/.meteor/local/build/programs/server/boot.js:175:10
W20150111-02:46:41.523(-8)? (STDERR)     at Array.forEach (native)
W20150111-02:46:41.528(-8)? (STDERR)     at Function._.each._.forEach (/Users/SavvyMac/.meteor/packages/meteor-tool/.1.0.38.ydz5xy++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150111-02:46:41.529(-8)? (STDERR)     at /Users/SavvyMac/code/meteor-learning/people-match/.meteor/local/build/programs/server/boot.js:86:5
```

There was another issue that mentioned a similar issue, and it was a `collection2` error. I don't have collection2 in my project (see below for potential package conflicts).

When I open up `meteor mongo`, I can run an `aggregate` query like this, and it returns results, so I know that your package is working: 
`db.metrics.aggregate([{ $match : { sport : 'NFL'}}, {$project: {contestName: 1, entrySize: 1}}])`

These are my packages: 
```
meteor-platform
coffeescript
jquery
accounts-ui
accounts-password
accounts-facebook
insecure
bengott:avatar
iron:router
multiply:iron-router-progress
fourseven:scss
nemo64:bootstrap
less
matteodem:easy-search
meteorhacks:fast-render@2.0.0-rc4
reywood:publish-composite
copleykj:livestamp
copleykj:jquery-autosize
accounts-twitter
zimme:iron-router-active
mquandalle:jade
maazalik:malihu-jquery-custom-scrollbar
momentjs:moment
msavin:sessioninspector
gwendall:session-json
matb33:collection-hooks
vjau:xml2js
http
natestrauser:font-awesome
meteorhacks:npm

mrt:moment-timezone
alanning:roles

npm-container
houston:admin
meteorhacks:kadira
meteorhacks:subs-manager
meteorhacks:aggregate
```

I tried to debug by 
1) commenting out packages that looked related to collections and their related Collection code
`matb33:collection-hooks` and `reywood:publish-composite` (the error persisted).

2) started a `meteor create ` project, tested out your aggregate code above (it worked properly). Then added in all the packages above, and ran the same code (it worked properly)

I'm not sure if you have any potential idea why this error is persisting. Thanks!!

**Comment by ericchen0121** [comment]
RESOLVED! The issue was actually a race condition between when the package loaded and when the `aggregate` function was called. 

When i moved the `meteorhacks:aggregate` package to the top of my `.meteor/packages` file after `meteor-platform` then it worked properly. 

When I moved it back to the bottom of my `.meteor/packages` file (after 20-30 other packages), it produced the same error as above. 

Is there a better solution than what I've done? Is there a "after all packages have loaded" function I can use to ensure my aggregate functions dont' run into this problem again?

**Comment by arunoda** [comment]
If you are using `.aggregate` inside a package(even with local packages), this race condition can be occurred. 

If that's the case, try to depend on `meteorhacks:aggregate` on that package. Then, `meteorhacks:aggregate` will come before your package.
